// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlEkSJL6lTYgfeJ37c18k3BDhqF6xoehM',
    appId: '1:935032860660:web:544b684ec2186e09bf93a1',
    messagingSenderId: '935032860660',
    projectId: 'm2tl-badff',
    authDomain: 'm2tl-badff.firebaseapp.com',
    storageBucket: 'm2tl-badff.appspot.com',
    measurementId: 'G-PHKCJSKE6H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuTmVYT9zmyZHOtdEPnHT71XBxZjNplp8',
    appId: '1:935032860660:android:eab7d46ea3e0e030bf93a1',
    messagingSenderId: '935032860660',
    projectId: 'm2tl-badff',
    storageBucket: 'm2tl-badff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9He-gpcPSToLbfsxQzPSg-JxlA02QLlU',
    appId: '1:935032860660:ios:69f9f491e6c8c09ebf93a1',
    messagingSenderId: '935032860660',
    projectId: 'm2tl-badff',
    storageBucket: 'm2tl-badff.appspot.com',
    iosClientId: '935032860660-221659365qdmqa4pkve8cmn9a0telrbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.m2tldigitalcampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9He-gpcPSToLbfsxQzPSg-JxlA02QLlU',
    appId: '1:935032860660:ios:69f9f491e6c8c09ebf93a1',
    messagingSenderId: '935032860660',
    projectId: 'm2tl-badff',
    storageBucket: 'm2tl-badff.appspot.com',
    iosClientId: '935032860660-221659365qdmqa4pkve8cmn9a0telrbe.apps.googleusercontent.com',
    iosBundleId: 'com.example.m2tldigitalcampus',
  );
}
