// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmCH7ZmxwMY_LLXQahVVHi4H1oD--qpDM',
    appId: '1:645310918219:web:aa4594b97c2277338c27ce',
    messagingSenderId: '645310918219',
    projectId: 'fluttermessages-ee767',
    authDomain: 'fluttermessages-ee767.firebaseapp.com',
    storageBucket: 'fluttermessages-ee767.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWlcpSKhpSnngkl6OXz0_xFp3aSBywxf4',
    appId: '1:645310918219:android:e4da4566e05d6dab8c27ce',
    messagingSenderId: '645310918219',
    projectId: 'fluttermessages-ee767',
    storageBucket: 'fluttermessages-ee767.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXVDmJyNYJNLdCiiXwJ61wM6XCbo-RVeM',
    appId: '1:645310918219:ios:1284535c7ddd3aa08c27ce',
    messagingSenderId: '645310918219',
    projectId: 'fluttermessages-ee767',
    storageBucket: 'fluttermessages-ee767.appspot.com',
    iosClientId: '645310918219-llf8pcd43k4ke0jgmblu845ms4pg9jd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.m2tldigitalcampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXVDmJyNYJNLdCiiXwJ61wM6XCbo-RVeM',
    appId: '1:645310918219:ios:1284535c7ddd3aa08c27ce',
    messagingSenderId: '645310918219',
    projectId: 'fluttermessages-ee767',
    storageBucket: 'fluttermessages-ee767.appspot.com',
    iosClientId: '645310918219-llf8pcd43k4ke0jgmblu845ms4pg9jd9.apps.googleusercontent.com',
    iosBundleId: 'com.example.m2tldigitalcampus',
  );
}
